name: 'Infrastructure - Production'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Terraform formate
        id: formate
        run: |
          terraform fmt -diff -write=true -recursive .
          terraform fmt

      - name: Install python packages & aws cli
        run: |
          python -m pip install --upgrade pip
          pip install pyhcl
          sudo apt update
          sudo apt install awscli -y
         
      - name: Configure AWS credentials
        run: |
          mkdir -p $HOME/.aws/
          touch $HOME/.aws/credentials
          echo "[default]" >> $HOME/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $HOME/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME
          
      - name: Execute lint script 
        run: python Infrastructure_Definition/bin/lint.py
      
      - name: Checking the last commit folder name 
        id: last_commit
        run: |
            last_commit=$(git log -1 --name-only --pretty=format:'' | xargs -n1 dirname | sort -u | head -1 | cut -d'/' -f1)
            if [[ $last_commit == "Stack_Definition" ]]; then
              echo "::set-output name=folder::true"
            else
              echo "::set-output name=folder::false"
            fi

      - name: Executing the provider script
        run: sh Infrastructure_Definition/bin/backend.sh
