name: 'Infrastructure - Production'

on:
  push:
    branches:
    - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Terraform formate
        id: formate
        run: |
          terraform fmt -diff -write=true -recursive .
          terraform fmt

      - name: Install python packages & aws cli
        run: |
          python -m pip install --upgrade pip
          pip install pyhcl
          sudo apt update
          sudo apt install awscli -y
          
      - name: Execute lint script 
        run: python Infrastructure_Definition/bin/lint.py
                
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"

      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
      
      - name: echo output
        run: |
           echo ${{ steps.getfile.outputs.files }}
      
      - name: Checking the last commit folder name 
        id: check_commit
        run: |
            folder=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
            echo $folder
          
      - name: Executing the provider script
        if: ${{ steps.check_commit.outputs.folder }} == 'Stack_Definition'
        run: sh Infrastructure_Definition/bin/backend.sh
