name: 'Master Infrastructure - Production'

on:
  push:
    paths:
      - 'Master_Definition/**'
      
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install python packages & aws cli
        run: |
          python -m pip install --upgrade pip
          pip install pyhcl
          sudo apt update
          sudo apt install awscli -y
          
      - name: Execute lint script 
        run: python Infrastructure_Definition/bin/master-lint.py
          